apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  annotations:
    argocd/app-name: postgres
spec:
  type: service
  owner: user:default/allturnbull
  lifecycle: production